

#MongoDB Configuration
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/Customer_Management
#Keycloak related configuration

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9009/realms/realm-customer
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs



jwt:
  auth:
    converter:
      resource-id: Client 1
      principle-attribute: preferred_username
